language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "4.2.0"
    - "iojs"

before_install:
    - npm install -g bower
    - bower install

before_script:
    - npm install -g gulp

script:
    - gulp scripts
